= Java 9
:toc:
:toclevels: 3
:toc-placement!:
:lb: pass:[<br> +]
:imagesdir: images
:icons: font
:source-highlighter: highlightjs
:sectnums:

toc::[]

== Overview

* Date de release 2017/03/23

== New features planned

=== Jigsaw

=== HTTP/2

La version actuellement supportée est toujours la 1.1, datant de 1999. +
La nouvelle API supportant la version 2 sera bien plus simple à utiliser (utilisatio du pattern *Builder*)

=== Process API

Mise à jour de l'API Process afin de simplifier la récupération et la gestion des processus systèmes :

[source,java]
----
// Get PIDs of own or started processes
out.println("Your pid is " + ProcessHandle.current().getPid());

Process p = Runtime.getRuntime().exec("sleep 1h");
ProcessHandle h = ProcessHandle.of(p.getPid())  // Optional
        .orElseThrow(IllegalStateException::new);

// Do things on exiting process          // CompletableFuture
h.onExit().thenRun( ()-> out.println("Sleeper exited") );

// Get info on process
out.printf("[%d] %s - %s\n", h.getPid(),
           h.info().user().orElse("unknown"),
           h.info().commandLine().orElse("none"));

// Kill a process
h.destroy();
----

=== REPL (JShell)

*REPL* = _Read Eval Print Loop_

Correspond au https://bugs.openjdk.java.net/browse/JDK-8043364[projet Kulla], maintenant connu comme *JShell*.

=== Immutable collection factories

Parmi les nombreux reproches faits à Java, son côté super verbeux revient souvent.
Pour une simple instanciation d'une collection de string, on souffre le martyr ! 
Voici un exemple :

[source,java]
----
Set<String> set = new HashSet<>();
set.add("a");
set.add("b");
set.add("c");
set = Collections.unmodifiableSet(set);
----
C'est pénible ! Une collection aussi triviale devait s'instancier en une ligne de code !
Il a fallu attendre Java 9 pour avoir cela (forte inspiration de Guava) :
[source,java]
----
/* Comment sections would break ... */
List<Integer> listOfNumbers = List.of(1, 2, 3, 4, 5/*, null*/);

Set<Integer> setOfNumbers = Set.of(1, 2, 3, 4, 5/*, 1*/);

Map<String, String> mapOfString =
    Map.of("key1", "value1", "key2", "value2");

Map<String, String> moreMapOfString =
    Map.ofEntries(
        Map.entry("key1", "value1"),
        Map.entry("key2", "value2")/*,
        Map.entry("key1", "value3")*/
);
----
Pour résumer on peut déclarer une collection non modifiable, dans laquelle on peut initialiser quelques élements.
ATTENTION :

* Le nombre d'élement à initialiser est limité ( je ne sais pas quel est nombre max )
* On ne peut pas initialiser par des NULL ( après j'admets que c'est assez tordu comme besoin)


=== HTML5 Javadoc

=== Garbage Collector G1

Devient le garbage collector par défaut

== Ressources

* https://bentolor.github.io/java9-in-action
* Programmez! 199
* http://openjdk.java.net/projects/jdk9/[la liste complète des évolutions prévues pour Java 9]
